my-app:
  messaging:
    consumer-route:
      "rabbitmq:my-topic?\
        exchangeType=topic&\
        durable=false&\
        autoDelete=true&\
        routingKey=consumer"
    record:
      route:
        "rabbitmq:record?\
          exchangeType=topic&\
          skipQueueDeclare=true&\
          durable=false&\
          autoDelete=true"
      key: record
    replay:
      route:
        "rabbitmq:replay?\
          exchangeType=topic&\
          durable=false&\
          autoDelete=true&\
          routingKey=replay"

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgresSQLDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres"
    name: springDatasource
    platform: postgresql
    driver-class-name: org.postgresql.Driver