my-app:
  messaging:
    consumer-route:
      "rabbitmq:my-topic?\
        exchangeType=topic&\
        durable=false&\
        autoDelete=true&\
        routingKey=consumer"
    record:
      route:
        "rabbitmq:record?\
          exchangeType=topic&\
          skipQueueDeclare=true&\
          durable=false&\
          autoDelete=true"
      key: record
    replay:
      route:
        "rabbitmq:replay?\
          exchangeType=topic&\
          durable=false&\
          autoDelete=true&\
          routingKey=replay"

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgresSQLDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres"
    name: springDatasource
    platform: postgresql
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      indent-output: false
      WRITE_DATES_AS_TIMESTAMPS: true
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
    deserialization:
      READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
      ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT: true

logging:
  level:
    miguel.oliveira.demo: DEBUG