my-app:
  messaging:
    consumer-route:
      "rabbitmq:my-topic?\
        exchangeType=topic&\
        durable=false&\
        autoDelete=true&\
        routingKey=consumer"
    record:
      route:
        "rabbitmq:record?\
          exchangeType=topic&\
          skipQueueDeclare=true&\
          durable=false&\
          autoDelete=true"
      key: record
    replay:
      route:
        "rabbitmq:replay?\
          exchangeType=topic&\
          durable=false&\
          autoDelete=true&\
          routingKey=replay"